import mongoose from "mongoose";

const postSchema = new mongoose.Schema({
    author:{
        type: String,
        required: true
    },
    title: {
        type: String,
        required: true
    },
    content: {
        type: String,
        required: true
    },
    summary: {
        type: String,
        default: ''  // Optional summary field, generated by AI
    },
    createdAt: {
        type: Date,
        default: Date.now
    }
});

//model
const BlogModel = mongoose.model("Blog", postSchema);
export default BlogModel;
